[workspace]
resolver = "2"

members = ["day-*"]
default-members = ["day-*"]

[workspace.dependencies]
indicatif = { version = "0.17.7", features = ["rayon"] }
nom = "7.1.3"
nom-supreme = "0.8.0"
rayon = "1.8.0"
rstest = "0.18.2"
